In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("../data/output/source_info.csv")
df

,Main,Source,RA,Dec,Dis,LBol,TBol,Class,SigmaYSO,group
0,Per-emb-22,Per-emb-22-B,51.343125,30.753650,300.0,NaN,74.8,NaN,NaN,perseus
1,Per-emb-22,Per-emb-22-A,51.343333,30.753669,300.0,NaN,130.5,NaN,NaN,perseus
2,L1448 IRS3C,L1448 IRS3C-A,51.398646,30.759450,300.0,NaN,115.8,NaN,NaN,perseus
3,L1448 IRS3C,L1448 IRS3C-B,51.398658,30.759517,300.0,NaN,79.6,NaN,NaN,perseus
4,Per-emb-33,Per-emb-33-B,51.401292,30.754192,300.0,NaN,49.3,NaN,NaN,perseus
...,...,...,...,...,...,...,...,...,...,...
132,HOPS-361,HOPS-361-G-B,86.772712,0.363911,430.4,503.00,69.0,0,91.3,orion
133,HOPS-364,HOPS-364-B,86.902308,0.335000,427.8,34.26,96.7,I,22.6,orion
134,HOPS-364,HOPS-364-A,86.902346,0.334978,427.8,34.26,96.7,I,22.6,orion
135,HH270VLA1,HH270VLA1-A,87.894113,2.946114,430.1,7.34,32.0,0,2.2,orion
136,HH270VLA1,HH270VLA1-B,87.894167,2.946078,430.1,7.34,32.0,0,2.2,orion

In [16]:
offsets = df[['Main', 'Source']]
offsets['dec_offset'] = 0
offsets['ra_offset'] = 0

/var/folders/41/_gkgvhb94wd4156zplzr4cg00000gn/T/ipykernel_9608/2822446290.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  offsets['dec_offset'] = 0
/var/folders/41/_gkgvhb94wd4156zplzr4cg00000gn/T/ipykernel_9608/2822446290.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  offsets['ra_offset'] = 0

In [17]:
offsets

            Main         Source  dec_offset  ra_offset
0     Per-emb-22   Per-emb-22-B           0          0
1     Per-emb-22   Per-emb-22-A           0          0
2    L1448 IRS3C  L1448 IRS3C-A           0          0
3    L1448 IRS3C  L1448 IRS3C-B           0          0
4     Per-emb-33   Per-emb-33-B           0          0
..           ...            ...         ...        ...
132     HOPS-361   HOPS-361-G-B           0          0
133     HOPS-364     HOPS-364-B           0          0
134     HOPS-364     HOPS-364-A           0          0
135    HH270VLA1    HH270VLA1-A           0          0
136    HH270VLA1    HH270VLA1-B           0          0

[137 rows x 4 columns]

In [18]:
offsets.to_csv("../data/input/offsets.csv",index=False)

In [19]:
df

,Main,Source,RA,Dec,Dis,LBol,TBol,Class,SigmaYSO,group
0,Per-emb-22,Per-emb-22-B,51.343125,30.753650,300.0,NaN,74.8,NaN,NaN,perseus
1,Per-emb-22,Per-emb-22-A,51.343333,30.753669,300.0,NaN,130.5,NaN,NaN,perseus
2,L1448 IRS3C,L1448 IRS3C-A,51.398646,30.759450,300.0,NaN,115.8,NaN,NaN,perseus
3,L1448 IRS3C,L1448 IRS3C-B,51.398658,30.759517,300.0,NaN,79.6,NaN,NaN,perseus
4,Per-emb-33,Per-emb-33-B,51.401292,30.754192,300.0,NaN,49.3,NaN,NaN,perseus
...,...,...,...,...,...,...,...,...,...,...
132,HOPS-361,HOPS-361-G-B,86.772712,0.363911,430.4,503.00,69.0,0,91.3,orion
133,HOPS-364,HOPS-364-B,86.902308,0.335000,427.8,34.26,96.7,I,22.6,orion
134,HOPS-364,HOPS-364-A,86.902346,0.334978,427.8,34.26,96.7,I,22.6,orion
135,HH270VLA1,HH270VLA1-A,87.894113,2.946114,430.1,7.34,32.0,0,2.2,orion
136,HH270VLA1,HH270VLA1-B,87.894167,2.946078,430.1,7.34,32.0,0,2.2,orion

In [ ]:
df['RA'] = df['RA'] + offsets['ra_offset'] / 3600