In [43]:
import numpy as np
import astropy.io.ascii
import pandas as pd
import matplotlib.pyplot as plt

In [44]:
# Binaries w/ 1 Outflow
cat_1 = [
    "HH270VLA1",
    "HOPS-323",
    "HOPS-312",
    "HOPS-364",
    "HOPS-45",
    "HOPS-361", # file is named 361-N
    "HOPS-366", 
    "HOPS-384",
    "HOPS-304",
    "HOPS-357",
    "HOPS-363",
    "HOPS-400",
    "HOPS-56",
    "HOPS-193",
    "HOPS-242",
    "HOPS-70",
    "HOPS-138",
    "HOPS-85",
    "HOPS-182",
    "HOPS-28",
    "HOPS-32",
    "HOPS-158",
    "HOPS-75",
    "HOPS-395",
    "HOPS-43",
    "HOPS-255",
    "HOPS-213",
    "HOPS-77",
    "HOPS-281",
    "HOPS-173",
    "HOPS-282",
    "HOPS-84",
    "HOPS-248",
    "HOPS-168",
    "HOPS-163",
    "HOPS-261",
    "Per-emb-2",
    "Per-emb-5",
    "Per-emb-17",
    "Per-emb-18",
    "Per-emb-22",
    "Per-emb-36",
    "Per-emb-44",
]

# Binaries w/ 2 Outflows
cat_2 = [
    "HOPS-290",
    "Per-emb-12",
    "Per-emb-27",
    "Per-emb-35",
    "Per-emb-33",
]

# Hierarchical Triples w/ 2 Outflows
cat_3 = [
    "HOPS-12",
    "HOPS-92",
    "HOPS-203",
    "HOPS-288",

]

In [45]:
df = pd.read_csv("../data/output/outflow_data.csv")
df = df[['group', 'field', 'outflow_source', 'outflow_PA', 'binary_PA', 'delta_PA']]
df = df[df['field'].isin(cat_1)]
# df['source_a'] = df['field'] + '-' + df['source_a']
# df['source_b'] = df['field'] + '-' + df['source_b']

In [46]:
df

      group       field outflow_source  outflow_PA   binary_PA   delta_PA
10    orion   HH270VLA1           both    230.0425  123.690068  73.647568
11    orion     HOPS-32              B    339.0450  232.853313  73.808313
12    orion     HOPS-84           both    262.8150  209.491362  53.323638
13    orion    HOPS-168           both    339.3500   58.781597  79.431597
14    orion    HOPS-281              A    206.0200  253.009177  46.989177
15    orion    HOPS-312           both     36.3725  136.847610  79.524890
16    orion    HOPS-364           both     96.3025  300.650668  24.348168
17    orion    HOPS-395              B    354.1675  263.088773  88.921273
18    orion    HOPS-400              A     86.6450  158.078221  71.433221
19    orion    HOPS-182           both     54.6425  197.700428  36.942072
20    orion    HOPS-323           both    123.0900  224.370401  78.719599
21    orion    HOPS-282           both      2.9800  263.088773  80.108773
22    orion    HOPS-366           both    316.6200   36.869898  80.249898
23    orion    HOPS-193           both    273.6425  176.698134  83.055634
24    orion    HOPS-304           both    151.5850  251.565051  80.019949
26    orion    HOPS-384           both      4.3700   39.805571  35.435571
27    orion    HOPS-363           both    272.8100  123.690068  30.880068
28    orion    HOPS-173           both     66.9900  145.713123  78.723123
29    orion     HOPS-75           both    276.5275  186.842773  89.684727
30    orion    HOPS-213              B     84.4875  319.028264  54.540764
31  perseus   Per-emb-2              B    126.1725  327.264774  21.092274
34  perseus  Per-emb-17           both    235.6500  146.888658  88.761342
35  perseus  Per-emb-18           both    166.5450  259.215702  87.329298
36  perseus  Per-emb-22           both    308.8350  264.667841  44.167159
43  perseus  Per-emb-36           both    244.4600    0.000000  64.460000
44  perseus  Per-emb-44           both    162.9750  268.090848  74.884152

In [47]:
sep = pd.read_csv('../data/output/separations.csv')
sep = sep.rename(columns={'PSep': 'separation', 'Class': 'class'})

In [48]:
df = df.merge(sep, left_on='field', right_on='Pair', how='left').drop('Pair',axis=1)
df

,group,field,outflow_source,outflow_PA,binary_PA,delta_PA,separation,class
0,orion,HH270VLA1,both,230.0425,123.690068,73.647568,99.4,C0+C0
1,orion,HOPS-32,B,339.0450,232.853313,73.808313,162.2,C0+C0
2,orion,HOPS-84,both,262.8150,209.491362,53.323638,275.5,CI+CI
3,orion,HOPS-168,both,339.3500,58.781597,79.431597,73.7,C0+C0
4,orion,HOPS-281,A,206.0200,253.009177,46.989177,311.6,FS+FS
5,orion,HOPS-312,both,36.3725,136.847610,79.524890,134.7,C0+C0
6,orion,HOPS-364,both,96.3025,300.650668,24.348168,65.5,CI+CI
7,orion,HOPS-395,B,354.1675,263.088773,88.921273,65.4,C0+C0
8,orion,HOPS-400,A,86.6450,158.078221,71.433221,184.0,C0+C0
9,orion,HOPS-182,both,54.6425,197.700428,36.942072,381.5,C0+C0
10,orion,HOPS-323,both,123.0900,224.370401,78.719599,273.6,CI+CI
11,orion,HOPS-282,both,2.9800,263.088773,80.108773,70.1,CI+CI
12,orion,HOPS-366,both,316.6200,36.869898,80.249898,61.1,CI+CI
13,orion,HOPS-193,both,273.6425,176.698134,83.055634,100.0,CI+CI
14,orion,HOPS-304,both,151.5850,251.565051,80.019949,272.7,FS+FS
15,orion,HOPS-384,both,4.3700,39.805571,35.435571,49.0,C0+C0
16,orion,HOPS-363,both,272.8100,123.690068,30.880068,79.5,FS+FS
17,orion,HOPS-173,both,66.9900,145.713123,78.723123,103.0,C0+C0
18,orion,HOPS-75,both,276.5275,186.842773,89.684727,99.8,C0+C0
19,orion,HOPS-213,B,84.4875,319.028264,54.540764,114.4,FS+FS
20,perseus,Per-emb-2,B,126.1725,327.264774,21.092274,24.1,C0+C0
21,perseus,Per-emb-17,both,235.6500,146.888658,88.761342,83.4,C0+C0
22,perseus,Per-emb-18,both,166.5450,259.215702,87.329298,25.5,C0+C0
23,perseus,Per-emb-22,both,308.8350,264.667841,44.167159,225.4,C0+C0
24,perseus,Per-emb-36,both,244.4600,0.000000,64.460000,93.3,CI+CI
25,perseus,Per-emb-44,both,162.9750,268.090848,74.884152,90.1,C0+C0

In [49]:
print(df.to_latex(index=False))

\begin{tabular}{lllrrrrl}
\toprule
group & field & outflow_source & outflow_PA & binary_PA & delta_PA & separation & class \\
\midrule
orion & HH270VLA1 & both & 230.042500 & 123.690068 & 73.647568 & 99.400000 & C0+C0 \\
orion & HOPS-32 & B & 339.045000 & 232.853313 & 73.808313 & 162.200000 & C0+C0 \\
orion & HOPS-84 & both & 262.815000 & 209.491362 & 53.323638 & 275.500000 & CI+CI \\
orion & HOPS-168 & both & 339.350000 & 58.781597 & 79.431597 & 73.700000 & C0+C0 \\
orion & HOPS-281 & A & 206.020000 & 253.009177 & 46.989177 & 311.600000 & FS+FS \\
orion & HOPS-312 & both & 36.372500 & 136.847610 & 79.524890 & 134.700000 & C0+C0 \\
orion & HOPS-364 & both & 96.302500 & 300.650668 & 24.348168 & 65.500000 & CI+CI \\
orion & HOPS-395 & B & 354.167500 & 263.088773 & 88.921273 & 65.400000 & C0+C0 \\
orion & HOPS-400 & A & 86.645000 & 158.078221 & 71.433221 & 184.000000 & C0+C0 \\
orion & HOPS-182 & both & 54.642500 & 197.700428 & 36.942072 & 381.500000 & C0+C0 \\
orion & HOPS-323 & both & 123.090000 & 224.370401 & 78.719599 & 273.600000 & CI+CI \\
orion & HOPS-282 & both & 2.980000 & 263.088773 & 80.108773 & 70.100000 & CI+CI \\
orion & HOPS-366 & both & 316.620000 & 36.869898 & 80.249898 & 61.100000 & CI+CI \\
orion & HOPS-193 & both & 273.642500 & 176.698134 & 83.055634 & 100.000000 & CI+CI \\
orion & HOPS-304 & both & 151.585000 & 251.565051 & 80.019949 & 272.700000 & FS+FS \\
orion & HOPS-384 & both & 4.370000 & 39.805571 & 35.435571 & 49.000000 & C0+C0 \\
orion & HOPS-363 & both & 272.810000 & 123.690068 & 30.880068 & 79.500000 & FS+FS \\
orion & HOPS-173 & both & 66.990000 & 145.713123 & 78.723123 & 103.000000 & C0+C0 \\
orion & HOPS-75 & both & 276.527500 & 186.842773 & 89.684727 & 99.800000 & C0+C0 \\
orion & HOPS-213 & B & 84.487500 & 319.028264 & 54.540764 & 114.400000 & FS+FS \\
perseus & Per-emb-2 & B & 126.172500 & 327.264774 & 21.092274 & 24.100000 & C0+C0 \\
perseus & Per-emb-17 & both & 235.650000 & 146.888658 & 88.761342 & 83.400000 & C0+C0 \\
perseus & Per-emb-18 & both & 166.545000 & 259.215702 & 87.329298 & 25.500000 & C0+C0 \\
perseus & Per-emb-22 & both & 308.835000 & 264.667841 & 44.167159 & 225.400000 & C0+C0 \\
perseus & Per-emb-36 & both & 244.460000 & 0.000000 & 64.460000 & 93.300000 & CI+CI \\
perseus & Per-emb-44 & both & 162.975000 & 268.090848 & 74.884152 & 90.100000 & C0+C0 \\
\bottomrule
\end{tabular}