In [290]:
import numpy as np
import astropy.io.ascii
import pandas as pd
import matplotlib.pyplot as plt
from astropy.table import Table
from io import StringIO
from astropy import units as u

In [291]:
df = pd.read_csv("../data/output/outflow_data.csv")
sep = pd.read_csv('../data/output/separations.csv')
notes = pd.read_csv('../data/input/notes.csv')

In [292]:
def getIdx(listOf):
    ranges = []
    
    for string in listOf:
        if pd.isna(string):  # Skip NaN values
            continue
        
        for part in string.split(', '):
            if '-' in part:  # Handle ranges
                start, end = map(int, part.split('-'))
                ranges.append(np.r_[start:end + 1])  # Use np.r_
            else:  # Handle single values
                ranges.append(int(part))  # Append as integer
    
    # Ensure `ranges` is not empty before passing to np.r_
    if not ranges:
        return np.r_[:]  # Returns an empty np.r_

    return np.r_[tuple(ranges)]  # Use `tuple(ranges)` to avoid errors

df.loc[df['outflow_source'] == 'both', 'outflow_source'] = df.loc[df['outflow_source'] == 'both']['source_a'] + '+' + df.loc[df['outflow_source'] == 'both']['source_b']
df['integrated_channels'] = (df['red_channels'].fillna('') + ', ' + df['blue_channels'].fillna('')).str.lstrip(', ').str.rstrip(', ')
df['num_integrated_channels'] = df.apply(
    lambda row: len(getIdx([row['red_channels'], row['blue_channels']])), axis=1
)

In [293]:
by_outflow = df[['field', 'outflow_source', 'outflow_PA', 'binary_PA', 'delta_PA']]
by_outflow['tertiary'] = by_outflow['binary_PA'].isna()

by_outflow = pd.merge(by_outflow, sep, left_on=['field', 'tertiary'], right_on=['pair', 'tertiary'], how='left')
by_outflow['type'] = by_outflow['tertiary'].map({True: 'Tertiary', False: 'Binary'})
by_outflow = by_outflow.drop(['tertiary', 'pair'],axis=1).reset_index(drop=True)
by_outflow = by_outflow[['field', 'type', 'separation', 'class', 'outflow_source', 'outflow_PA', 'binary_PA', 'delta_PA']]
by_outflow = by_outflow.fillna('-')
by_outflow[['outflow_PA', 'binary_PA', 'delta_PA']] = by_outflow[['outflow_PA', 'binary_PA', 'delta_PA']].replace('-', np.nan).astype(float).round(0).astype('Int64')
by_outflow

/var/folders/41/_gkgvhb94wd4156zplzr4cg00000gn/T/ipykernel_30009/769593483.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  by_outflow['tertiary'] = by_outflow['binary_PA'].isna()
/var/folders/41/_gkgvhb94wd4156zplzr4cg00000gn/T/ipykernel_30009/769593483.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  by_outflow[['outflow_PA', 'binary_PA', 'delta_PA']] = by_outflow[['outflow_PA', 'binary_PA', 'delta_PA']].replace('-', np.nan).astype(float).round(0).astype('Int64')

,field,type,separation,class,outflow_source,outflow_PA,binary_PA,delta_PA
0,HOPS-12,Binary,80.6,C0,B-A,337,45,68
1,HOPS-12,Tertiary,1853.5,C0,A,337,<NA>,<NA>
2,HOPS-290,Binary,332.7,C0,A,114,298,5
3,HOPS-290,Binary,332.7,C0,B,49,298,70
4,HOPS-92,Binary,108.4,FS,A-A+A-B,256,209,47
5,HOPS-92,Tertiary,498.8,FS,B,89,<NA>,<NA>
6,HOPS-288,Binary,61.3,C0,A-A+A-B,236,150,86
7,HOPS-288,Tertiary,221.9,C0,B,32,<NA>,<NA>
8,HOPS-203,Binary,49.7,C0,A+B,324,201,57
9,HOPS-203,Tertiary,1085.5,C0,C,281,<NA>,<NA>
10,HH270VLA1,Binary,99.4,C0,A+B,230,124,74
11,HOPS-32,Binary,162.2,C0,B,339,233,74
12,HOPS-84,Binary,275.5,C1,A+B,263,209,53
13,HOPS-168,Binary,73.7,C0,A+B,339,59,79
14,HOPS-281,Binary,311.6,FS,A,206,253,47
15,HOPS-312,Binary,134.7,C0,A+B,36,137,80
16,HOPS-364,Binary,65.5,C1,A+B,96,301,24
17,HOPS-395,Binary,65.4,C0,B,354,263,89
18,HOPS-400,Binary,184.0,C0,A,87,158,71
19,HOPS-182,Binary,381.5,C0,A+B,55,198,37
20,HOPS-323,Binary,273.6,C1,A+B,123,224,79
21,HOPS-282,Binary,70.1,C1,A+B,3,263,80
22,HOPS-366,Binary,61.1,C1,A+B,317,37,80
23,HOPS-193,Binary,100.0,C1,A+B,274,177,83
24,HOPS-304,Binary,272.7,FS,A+B,152,252,80
25,HOPS-361-N,Binary,37.6,C0,C-A+C-B,21,288,87
26,HOPS-384,Binary,49.0,C0,A+A-B,4,40,35
27,HOPS-363,Binary,79.5,FS,A+B,273,124,31
28,HOPS-173,Binary,103.0,C0,A+B,67,146,79
29,HOPS-75,Binary,99.8,C0,A+B,277,187,90
30,HOPS-213,Binary,114.4,FS,B,84,319,55
31,Per-emb-2,Binary,24.1,C0,B,126,327,21
32,Per-emb-12,Binary,549.0,C0,B,208,308,80
33,Per-emb-12,Binary,549.0,C0,A,180,308,53
34,Per-emb-17,Binary,83.4,C0,A+B,236,147,89
35,Per-emb-18,Binary,25.5,C0,A+B,167,259,87
36,Per-emb-22,Binary,225.4,C0,A+B,309,265,44
37,Per-emb-27,Binary,186.0,C0,A,203,195,8
38,Per-emb-27,Binary,186.0,C0,B,294,195,81
39,Per-emb-33,Binary,79.6,C0,A+B,303,329,26
40,Per-emb-33,Tertiary,263.2,C0,C,288,<NA>,<NA>
41,Per-emb-35,Binary,572.5,C1,B,128,64,64
42,Per-emb-35,Binary,572.5,C1,A,119,64,55
43,Per-emb-36,Binary,93.3,C1,A+B,244,0,64
44,Per-emb-44,Binary,90.1,C0,A+B,163,268,75

In [294]:
t = Table.from_pandas(by_outflow)
buf = StringIO()
t.write(buf, format='ascii.latex', latexdict={'tabletype': 'deluxetable'})
print(buf.getvalue())

\begin{deluxetable}
\begin{tabular}{cccccccc}
field & type & separation & class & outflow_source & outflow_PA & binary_PA & delta_PA \\
HOPS-12 & Binary & 80.6 & C0 & B-A & 337 & 45 & 68 \\
HOPS-12 & Tertiary & 1853.5 & C0 & A & 337 &  &  \\
HOPS-290 & Binary & 332.7 & C0 & A & 114 & 298 & 5 \\
HOPS-290 & Binary & 332.7 & C0 & B & 49 & 298 & 70 \\
HOPS-92 & Binary & 108.4 & FS & A-A+A-B & 256 & 209 & 47 \\
HOPS-92 & Tertiary & 498.8 & FS & B & 89 &  &  \\
HOPS-288 & Binary & 61.3 & C0 & A-A+A-B & 236 & 150 & 86 \\
HOPS-288 & Tertiary & 221.9 & C0 & B & 32 &  &  \\
HOPS-203 & Binary & 49.7 & C0 & A+B & 324 & 201 & 57 \\
HOPS-203 & Tertiary & 1085.5 & C0 & C & 281 &  &  \\
HH270VLA1 & Binary & 99.4 & C0 & A+B & 230 & 124 & 74 \\
HOPS-32 & Binary & 162.2 & C0 & B & 339 & 233 & 74 \\
HOPS-84 & Binary & 275.5 & C1 & A+B & 263 & 209 & 53 \\
HOPS-168 & Binary & 73.7 & C0 & A+B & 339 & 59 & 79 \\
HOPS-281 & Binary & 311.6 & FS & A & 206 & 253 & 47 \\
HOPS-312 & Binary & 134.7 & C0 & A+B & 36 & 137 & 80 \\
HOPS-364 & Binary & 65.5 & C1 & A+B & 96 & 301 & 24 \\
HOPS-395 & Binary & 65.4 & C0 & B & 354 & 263 & 89 \\
HOPS-400 & Binary & 184.0 & C0 & A & 87 & 158 & 71 \\
HOPS-182 & Binary & 381.5 & C0 & A+B & 55 & 198 & 37 \\
HOPS-323 & Binary & 273.6 & C1 & A+B & 123 & 224 & 79 \\
HOPS-282 & Binary & 70.1 & C1 & A+B & 3 & 263 & 80 \\
HOPS-366 & Binary & 61.1 & C1 & A+B & 317 & 37 & 80 \\
HOPS-193 & Binary & 100.0 & C1 & A+B & 274 & 177 & 83 \\
HOPS-304 & Binary & 272.7 & FS & A+B & 152 & 252 & 80 \\
HOPS-361-N & Binary & 37.6 & C0 & C-A+C-B & 21 & 288 & 87 \\
HOPS-384 & Binary & 49.0 & C0 & A+A-B & 4 & 40 & 35 \\
HOPS-363 & Binary & 79.5 & FS & A+B & 273 & 124 & 31 \\
HOPS-173 & Binary & 103.0 & C0 & A+B & 67 & 146 & 79 \\
HOPS-75 & Binary & 99.8 & C0 & A+B & 277 & 187 & 90 \\
HOPS-213 & Binary & 114.4 & FS & B & 84 & 319 & 55 \\
Per-emb-2 & Binary & 24.1 & C0 & B & 126 & 327 & 21 \\
Per-emb-12 & Binary & 549.0 & C0 & B & 208 & 308 & 80 \\
Per-emb-12 & Binary & 549.0 & C0 & A & 180 & 308 & 53 \\
Per-emb-17 & Binary & 83.4 & C0 & A+B & 236 & 147 & 89 \\
Per-emb-18 & Binary & 25.5 & C0 & A+B & 167 & 259 & 87 \\
Per-emb-22 & Binary & 225.4 & C0 & A+B & 309 & 265 & 44 \\
Per-emb-27 & Binary & 186.0 & C0 & A & 203 & 195 & 8 \\
Per-emb-27 & Binary & 186.0 & C0 & B & 294 & 195 & 81 \\
Per-emb-33 & Binary & 79.6 & C0 & A+B & 303 & 329 & 26 \\
Per-emb-33 & Tertiary & 263.2 & C0 & C & 288 &  &  \\
Per-emb-35 & Binary & 572.5 & C1 & B & 128 & 64 & 64 \\
Per-emb-35 & Binary & 572.5 & C1 & A & 119 & 64 & 55 \\
Per-emb-36 & Binary & 93.3 & C1 & A+B & 244 & 0 & 64 \\
Per-emb-44 & Binary & 90.1 & C0 & A+B & 163 & 268 & 75 \\
\end{tabular}
\end{deluxetable}

In [295]:
by_field = df.groupby(['field']).agg('first').reset_index()[['field', 'source_a_ra', 'source_a_dec', 'integrated_channels', 'num_integrated_channels']]
notes = notes.groupby('Field').agg('first').reset_index()[['Field', 'N', 'V_sys']].dropna()
by_field = pd.merge(by_field, notes, left_on='field', right_on='Field', how='left')
by_field = by_field.rename(columns={'source_a_ra': 'ra', 'source_a_dec': 'dec', 'N': 'n_sources', 'V_sys': 'v_sys'})
by_field = by_field[['field', 'n_sources', 'ra', 'dec', 'v_sys', 'integrated_channels', 'num_integrated_channels']]
by_field[['ra', 'dec']] = by_field[['ra', 'dec']].round(5)
by_field[['n_sources']] = by_field[['n_sources']].round(0).astype(int)
by_field[['v_sys']] = by_field[['v_sys']].round(1)
by_field

,field,n_sources,ra,dec,v_sys,integrated_channels,num_integrated_channels
0,HH270VLA1,2,87.89411,2.94611,9.0,"94-100, 104-109",13
1,HOPS-12,3,83.78727,-5.93195,8.5,"92-97, 103-107",11
2,HOPS-168,2,84.07892,-6.75655,9.0,"91-98, 104-115",20
3,HOPS-173,2,84.10850,-6.41808,7.5,102,1
4,HOPS-182,3,84.07831,-6.36950,7.5,"88-93, 104-107",10
5,HOPS-193,2,84.12617,-6.02142,8.5,"97-99, 104",4
6,HOPS-203,3,84.09527,-6.76851,10.0,96-100,5
7,HOPS-213,2,85.70037,-8.66902,3.0,"92-93, 97-98",4
8,HOPS-281,2,85.10270,-7.71893,4.5,"91-94, 99-105",11
9,HOPS-282,2,85.10871,-7.62558,5.0,"93-95, 99-101",6
10,HOPS-288,3,84.98334,-7.50766,5.0,85-91,7
11,HOPS-290,2,84.98907,-7.49253,5.0,"91-94, 99-102",8
12,HOPS-304,2,85.44148,-1.94072,10.0,"94-98, 107-109",8
13,HOPS-312,2,85.77371,-1.26516,3.0,"88-91, 97-98",6
14,HOPS-32,2,83.64772,-5.66648,8.5,"95-98, 102-106",9
15,HOPS-323,2,86.69874,0.00702,11.0,"94-99, 105-107",9
16,HOPS-361-N,4,86.76930,0.36329,9.0,81-88,8
17,HOPS-363,2,86.67968,0.01454,9.0,"92-93, 107-109",5
18,HOPS-364,2,86.90235,0.33498,10.0,"94-98, 105-108",9
19,HOPS-366,2,86.76668,0.36954,9.0,"80-87, 112-120",17
20,HOPS-384,4,85.43390,-1.91279,11.0,108-112,5
21,HOPS-395,2,84.82122,-7.40682,5.0,"94-95, 98",3
22,HOPS-400,2,85.68852,-1.27045,9.0,"95-98, 103-108",10
23,HOPS-75,2,83.86117,-5.10292,11.0,"100-101, 106-107",4
24,HOPS-84,2,83.86067,-5.06531,10.5,"98-100, 104, 106-107",6
25,HOPS-92,3,83.82640,-5.00915,10.0,106-112,7
26,Per-emb-12,2,52.29388,31.22528,8.0,"140-147, 159-164",14
27,Per-emb-17,2,51.91292,30.21752,6.0,"144-148, 156-162",12
28,Per-emb-18,2,52.29695,31.30861,8.6,160-165,6
29,Per-emb-2,2,53.07473,30.82990,6.6,"146-150, 158-163",11
30,Per-emb-22,2,51.34333,30.75367,4.0,"138-144, 155-170",23
31,Per-emb-27,2,52.23154,31.24360,8.0,"142-148, 161-165",12
32,Per-emb-33,3,51.40133,30.75412,4.0,154-164,11
33,Per-emb-35,2,52.15454,31.22521,8.6,159-163,5
34,Per-emb-36,2,52.23904,31.23772,8.0,162-167,6
35,Per-emb-44,2,52.26567,31.26772,8.0,169-175,7

In [296]:
t = Table.from_pandas(by_field)
buf = StringIO()
t.write(buf, format='ascii.latex', latexdict={'tabletype': 'deluxetable'})
print(buf.getvalue())

\begin{deluxetable}
\begin{tabular}{ccccccc}
field & n_sources & ra & dec & v_sys & integrated_channels & num_integrated_channels \\
HH270VLA1 & 2 & 87.89411 & 2.94611 & 9.0 & 94-100, 104-109 & 13 \\
HOPS-12 & 3 & 83.78727 & -5.93195 & 8.5 & 92-97, 103-107 & 11 \\
HOPS-168 & 2 & 84.07892 & -6.75655 & 9.0 & 91-98, 104-115 & 20 \\
HOPS-173 & 2 & 84.1085 & -6.41808 & 7.5 & 102 & 1 \\
HOPS-182 & 3 & 84.07831 & -6.3695 & 7.5 & 88-93, 104-107 & 10 \\
HOPS-193 & 2 & 84.12617 & -6.02142 & 8.5 & 97-99, 104 & 4 \\
HOPS-203 & 3 & 84.09527 & -6.76851 & 10.0 & 96-100 & 5 \\
HOPS-213 & 2 & 85.70037 & -8.66902 & 3.0 & 92-93, 97-98 & 4 \\
HOPS-281 & 2 & 85.1027 & -7.71893 & 4.5 & 91-94, 99-105 & 11 \\
HOPS-282 & 2 & 85.10871 & -7.62558 & 5.0 & 93-95, 99-101 & 6 \\
HOPS-288 & 3 & 84.98334 & -7.50766 & 5.0 & 85-91 & 7 \\
HOPS-290 & 2 & 84.98907 & -7.49253 & 5.0 & 91-94, 99-102 & 8 \\
HOPS-304 & 2 & 85.44148 & -1.94072 & 10.0 & 94-98, 107-109 & 8 \\
HOPS-312 & 2 & 85.77371 & -1.26516 & 3.0 & 88-91, 97-98 & 6 \\
HOPS-32 & 2 & 83.64772 & -5.66648 & 8.5 & 95-98, 102-106 & 9 \\
HOPS-323 & 2 & 86.69874 & 0.00702 & 11.0 & 94-99, 105-107 & 9 \\
HOPS-361-N & 4 & 86.7693 & 0.36329 & 9.0 & 81-88 & 8 \\
HOPS-363 & 2 & 86.67968 & 0.01454 & 9.0 & 92-93, 107-109 & 5 \\
HOPS-364 & 2 & 86.90235 & 0.33498 & 10.0 & 94-98, 105-108 & 9 \\
HOPS-366 & 2 & 86.76668 & 0.36954 & 9.0 & 80-87, 112-120 & 17 \\
HOPS-384 & 4 & 85.4339 & -1.91279 & 11.0 & 108-112 & 5 \\
HOPS-395 & 2 & 84.82122 & -7.40682 & 5.0 & 94-95, 98 & 3 \\
HOPS-400 & 2 & 85.68852 & -1.27045 & 9.0 & 95-98, 103-108 & 10 \\
HOPS-75 & 2 & 83.86117 & -5.10292 & 11.0 & 100-101, 106-107 & 4 \\
HOPS-84 & 2 & 83.86067 & -5.06531 & 10.5 & 98-100, 104, 106-107 & 6 \\
HOPS-92 & 3 & 83.8264 & -5.00915 & 10.0 & 106-112 & 7 \\
Per-emb-12 & 2 & 52.29388 & 31.22528 & 8.0 & 140-147, 159-164 & 14 \\
Per-emb-17 & 2 & 51.91292 & 30.21752 & 6.0 & 144-148, 156-162 & 12 \\
Per-emb-18 & 2 & 52.29695 & 31.30861 & 8.6 & 160-165 & 6 \\
Per-emb-2 & 2 & 53.07473 & 30.8299 & 6.6 & 146-150, 158-163 & 11 \\
Per-emb-22 & 2 & 51.34333 & 30.75367 & 4.0 & 138-144, 155-170 & 23 \\
Per-emb-27 & 2 & 52.23154 & 31.2436 & 8.0 & 142-148, 161-165 & 12 \\
Per-emb-33 & 3 & 51.40133 & 30.75412 & 4.0 & 154-164 & 11 \\
Per-emb-35 & 2 & 52.15454 & 31.22521 & 8.6 & 159-163 & 5 \\
Per-emb-36 & 2 & 52.23904 & 31.23772 & 8.0 & 162-167 & 6 \\
Per-emb-44 & 2 & 52.26567 & 31.26772 & 8.0 & 169-175 & 7 \\
\end{tabular}
\end{deluxetable}